name: $(version).$(Rev:r)

variables:
  version: 5.4
  buildConfiguration: "Release"
  imageRepository: "emberstack/kubernetes-reflector"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - src/*
      - .devops/*
      - azure-pipelines.yaml

stages:
  - template: .devops/pipelines/stage.ci.yaml
    parameters:
      architectures:
        - arch: amd64
          pool: winromulus-devops
        - arch: arm
          pool: winromulus-devops
        - arch: arm64
          pool: winromulus-devops

  - template: .devops/pipelines/stage.cd.yaml
    parameters:
      architectures:
        - arch: amd64
        - arch: arm
        - arch: arm64
